/**
 * Testable domain logic shared by the pkgref CLI workflow.
 */
import { readFile, readdir } from "node:fs/promises";
import { basename, join, posix, relative, sep } from "node:path";

export const INDEX_MARKER = "<!-- generated by pkgref; do not edit -->";
export const AGENTS_REFERENCE_START = "<!-- PKGREF START -->";
export const AGENTS_REFERENCE_END = "<!-- PKGREF END -->";

const DEPENDENCY_FIELDS = [
  "dependencies",
  "devDependencies",
  "peerDependencies",
  "optionalDependencies",
] as const;
const REFERENCE_DIRECTORIES = new Set(["doc", "docs", "example", "examples"]);

export interface PackageManifest {
  name?: string;
  version?: string;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
}

export interface RepositoryMetadata {
  type?: string;
  url?: string;
  directory?: string;
}

export interface RegistryPackage {
  repository?: string | RepositoryMetadata;
}

export interface RepositoryRef {
  cloneUrl: string;
  key: string;
  name: string;
}

export interface RepositoryGroup extends RepositoryRef {
  packages: string[];
}

export interface IndexRepository {
  directory: string;
  packages: string[];
  root: string;
}

export interface ReferenceDirectory {
  label: string;
  path: string;
}

export function discoverDependencies(manifest: PackageManifest): string[] {
  const names = new Set<string>();

  for (const field of DEPENDENCY_FIELDS) {
    const dependencies = manifest[field];
    if (!dependencies || typeof dependencies !== "object" || Array.isArray(dependencies)) {
      continue;
    }
    for (const name of Object.keys(dependencies)) {
      names.add(name);
    }
  }

  return [...names].sort((left, right) => left.localeCompare(right));
}

export async function readManifest(path: string): Promise<PackageManifest> {
  let contents: string;
  try {
    contents = await readFile(path, "utf8");
  } catch (error) {
    throw new Error(`Cannot read package manifest at ${path}: ${errorMessage(error)}`);
  }

  try {
    const manifest: unknown = JSON.parse(contents);
    if (!manifest || typeof manifest !== "object" || Array.isArray(manifest)) {
      throw new TypeError("expected a JSON object");
    }
    return manifest as PackageManifest;
  } catch (error) {
    throw new Error(`Invalid package manifest at ${path}: ${errorMessage(error)}`);
  }
}

export function parsePackageList(value: string): string[] {
  return [
    ...new Set(
      value
        .split(",")
        .map((name) => name.trim())
        .filter(Boolean),
    ),
  ];
}

export function renderAgentsReference(contents: string, indexPath: string): string {
  const block = [
    AGENTS_REFERENCE_START,
    "",
    "## Package references",
    "",
    "Before working with dependency APIs, consult the",
    `[package reference index](${indexPath}).`,
    "It links to cloned upstream documentation and examples.",
    "",
    AGENTS_REFERENCE_END,
  ].join("\n");
  const start = contents.indexOf(AGENTS_REFERENCE_START);
  const end = contents.indexOf(AGENTS_REFERENCE_END);

  if (start >= 0 && end >= start) {
    const suffixStart = end + AGENTS_REFERENCE_END.length;
    return `${contents.slice(0, start)}${block}${contents.slice(suffixStart)}`.trimEnd() + "\n";
  }

  return contents.trim() ? `${contents.trimEnd()}\n\n${block}\n` : `${block}\n`;
}

export function repositoryFromMetadata(metadata: RegistryPackage): RepositoryRef {
  const repository = metadata.repository;
  const rawUrl = typeof repository === "string" ? repository : repository?.url;
  if (!rawUrl) {
    throw new Error("package metadata does not declare a repository");
  }
  return normalizeRepository(rawUrl);
}

export function normalizeRepository(rawUrl: string): RepositoryRef {
  let cloneUrl = rawUrl.trim();
  if (!cloneUrl) {
    throw new Error("repository URL is empty");
  }

  cloneUrl = cloneUrl.replace(/^git\+/, "");
  if (/^github:[^/]+\/[^/]+$/i.test(cloneUrl)) {
    cloneUrl = `https://github.com/${cloneUrl.slice("github:".length)}`;
  } else if (/^[\w.-]+\/[\w.-]+$/.test(cloneUrl)) {
    cloneUrl = `https://github.com/${cloneUrl}`;
  } else if (/^git@[^:]+:.+/.test(cloneUrl)) {
    const match = /^git@([^:]+):(.+)$/.exec(cloneUrl);
    if (match) {
      cloneUrl = `ssh://git@${match[1]}/${match[2]}`;
    }
  } else if (cloneUrl.startsWith("git://")) {
    cloneUrl = `https://${cloneUrl.slice("git://".length)}`;
  }

  let parsed: URL;
  try {
    parsed = new URL(cloneUrl);
  } catch {
    throw new Error(`unsupported repository URL: ${rawUrl}`);
  }

  if (!["https:", "http:", "ssh:"].includes(parsed.protocol)) {
    throw new Error(`unsupported repository protocol: ${parsed.protocol}`);
  }

  const pathname = parsed.pathname.replace(/^\/+|\/+$/g, "").replace(/\.git$/i, "");
  if (!parsed.hostname || !pathname) {
    throw new Error(`invalid repository URL: ${rawUrl}`);
  }

  const name = basename(pathname);
  if (!name || name === "." || name === "..") {
    throw new Error(`cannot derive a repository name from ${rawUrl}`);
  }

  const credentials = parsed.protocol === "ssh:" && parsed.username ? `${parsed.username}@` : "";
  const normalizedPath = `${pathname}.git`;
  const normalizedCloneUrl =
    parsed.protocol === "ssh:"
      ? `ssh://${credentials}${parsed.hostname}/${normalizedPath}`
      : `${parsed.protocol}//${parsed.host}/${normalizedPath}`;

  return {
    cloneUrl: normalizedCloneUrl,
    key: `${parsed.hostname.toLowerCase()}/${pathname.toLowerCase()}`,
    name,
  };
}

export function groupRepositories(
  packages: Array<{ name: string; repository: RepositoryRef }>,
): RepositoryGroup[] {
  const byKey = new Map<string, RepositoryGroup>();
  const nameOwners = new Map<string, string>();

  for (const item of packages) {
    const existingNameOwner = nameOwners.get(item.repository.name);
    if (existingNameOwner && existingNameOwner !== item.repository.key) {
      throw new Error(
        `repository folder collision: different repositories resolve to "${item.repository.name}"`,
      );
    }
    nameOwners.set(item.repository.name, item.repository.key);

    const existing = byKey.get(item.repository.key);
    if (existing) {
      existing.packages.push(item.name);
    } else {
      byKey.set(item.repository.key, {
        ...item.repository,
        packages: [item.name],
      });
    }
  }

  return [...byKey.values()]
    .map((group) => ({
      ...group,
      packages: [...new Set(group.packages)].sort((left, right) => left.localeCompare(right)),
    }))
    .sort((left, right) => left.name.localeCompare(right.name));
}

export async function findReferenceDirectories(
  repositoryRoot: string,
  targetRoot: string,
): Promise<ReferenceDirectory[]> {
  const directories: ReferenceDirectory[] = [];

  async function walk(directory: string): Promise<void> {
    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((left, right) => left.name.localeCompare(right.name));

    for (const entry of entries) {
      if (entry.name === ".git" || (entry.isDirectory() && entry.name.startsWith("."))) {
        continue;
      }

      const fullPath = join(directory, entry.name);
      if (entry.isDirectory()) {
        if (REFERENCE_DIRECTORIES.has(entry.name.toLowerCase())) {
          directories.push({
            label: toPosixPath(relative(repositoryRoot, fullPath)),
            path: toPosixPath(relative(targetRoot, fullPath)),
          });
        } else {
          await walk(fullPath);
        }
      }
    }
  }

  await walk(repositoryRoot);
  return directories.sort((left, right) => left.path.localeCompare(right.path));
}

export async function renderIndex(
  repositories: IndexRepository[],
  targetRoot: string,
): Promise<string> {
  const lines = [INDEX_MARKER, "", "# Package references", ""];

  for (const repository of [...repositories].sort((left, right) =>
    left.directory.localeCompare(right.directory),
  )) {
    lines.push(`## ${repository.directory}`, "");
    lines.push(
      `Packages: ${[...repository.packages]
        .sort((left, right) => left.localeCompare(right))
        .map((packageName) => `\`${packageName}\``)
        .join(", ")}`,
      "",
    );

    const directories = await findReferenceDirectories(repository.root, targetRoot);
    if (directories.length === 0) {
      const repositoryPath = encodeLinkPath(toPosixPath(relative(targetRoot, repository.root)));
      lines.push(`- [Repository root](./${repositoryPath})`, "");
      continue;
    }

    for (const directory of directories) {
      const href = encodeLinkPath(directory.path);
      lines.push(`- [${escapeMarkdownLabel(directory.label)}](./${href})`);
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function mergeIndexes(existing: string, generated: string): string {
  const existingIndex = splitIndex(existing);
  const generatedIndex = splitIndex(generated);
  const sections = new Map(existingIndex.sections);

  for (const [repository, section] of generatedIndex.sections) {
    sections.set(repository, section);
  }

  const mergedSections = [...sections.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([, section]) => section);

  return `${[existingIndex.preamble, ...mergedSections].filter(Boolean).join("\n\n").trimEnd()}\n`;
}

export function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function toPosixPath(path: string): string {
  return sep === posix.sep ? path : path.split(sep).join(posix.sep);
}

function encodeLinkPath(path: string): string {
  return path
    .split("/")
    .map((part) => encodeURIComponent(part))
    .join("/");
}

function escapeMarkdownLabel(label: string): string {
  return label.replaceAll("\\", "\\\\").replaceAll("[", "\\[").replaceAll("]", "\\]");
}

function splitIndex(contents: string): {
  preamble: string;
  sections: Map<string, string>;
} {
  const matches = [...contents.matchAll(/^## (.+)$/gm)];
  const preamble = contents.slice(0, matches[0]?.index ?? contents.length).trimEnd();
  const sections = new Map<string, string>();

  for (const [index, match] of matches.entries()) {
    const start = match.index;
    const end = matches[index + 1]?.index ?? contents.length;
    sections.set(match[1].trim(), contents.slice(start, end).trimEnd());
  }

  return { preamble, sections };
}
