import { readFile, readdir } from "node:fs/promises";
import { basename, join, relative, sep } from "node:path";
import type {
  IndexRepository,
  PackageManifest,
  RegistryPackage,
  RepositoryGroup,
  RepositoryRef,
} from "./types.ts";

export const INDEX_MARKER = "<!-- generated by pkgref; do not edit -->";
const AGENTS_START = "<!-- PKGREF START -->";
const AGENTS_END = "<!-- PKGREF END -->";
const DEPENDENCY_FIELDS = [
  "dependencies",
  "devDependencies",
  "peerDependencies",
  "optionalDependencies",
] as const;
const REFERENCE_DIRECTORIES = new Set(["doc", "docs", "example", "examples"]);
const byName = <T extends { name: string }>(a: T, b: T) => a.name.localeCompare(b.name);

export function discoverDependencies(manifest: PackageManifest): string[] {
  return [
    ...new Set(DEPENDENCY_FIELDS.flatMap((field) => Object.keys(manifest[field] ?? {}))),
  ].sort();
}

export async function readManifest(path: string): Promise<PackageManifest> {
  try {
    const manifest: unknown = JSON.parse(await readFile(path, "utf8"));
    if (!manifest || typeof manifest !== "object" || Array.isArray(manifest)) {
      throw new Error("expected a JSON object");
    }
    return manifest as PackageManifest;
  } catch (error) {
    const action = (error as NodeJS.ErrnoException).code ? "Cannot read" : "Invalid";
    throw new Error(`${action} package manifest at ${path}: ${errorMessage(error)}`);
  }
}

export function parsePackageList(value: string): string[] {
  return [
    ...new Set(
      value
        .split(",")
        .map((name) => name.trim())
        .filter(Boolean),
    ),
  ];
}

export function renderAgentsReference(contents: string, indexPath: string): string {
  const block = `${AGENTS_START}

## Package references

Before working with dependency APIs, consult the
[package reference index](${indexPath}).
It links to cloned upstream documentation and examples.

${AGENTS_END}`;
  const marked = new RegExp(`${AGENTS_START}[\\s\\S]*?${AGENTS_END}`);
  const result = marked.test(contents)
    ? contents.replace(marked, block)
    : contents.trim()
      ? `${contents.trimEnd()}\n\n${block}`
      : block;
  return `${result.trimEnd()}\n`;
}

export function repositoryFromMetadata(metadata: RegistryPackage): RepositoryRef {
  const repository = metadata.repository;
  const url = typeof repository === "string" ? repository : repository?.url;
  if (!url) {
    throw new Error("package metadata does not declare a repository");
  }
  return normalizeRepository(url);
}

export function normalizeRepository(rawUrl: string): RepositoryRef {
  let url = rawUrl.trim().replace(/^git\+/, "");
  if (!url) {
    throw new Error("repository URL is empty");
  }
  if (/^github:/i.test(url)) {
    url = `https://github.com/${url.slice(7)}`;
  } else if (/^[\w.-]+\/[\w.-]+$/.test(url)) {
    url = `https://github.com/${url}`;
  } else if (/^git@[^:]+:/.test(url)) {
    url = url.replace(/^git@([^:]+):/, "ssh://git@$1/");
  } else if (url.startsWith("git://")) {
    url = `https://${url.slice(6)}`;
  }

  if (!URL.canParse(url)) {
    throw new Error(`unsupported repository URL: ${rawUrl}`);
  }
  const parsed = new URL(url);
  if (!["http:", "https:", "ssh:"].includes(parsed.protocol)) {
    throw new Error(`unsupported repository protocol: ${parsed.protocol}`);
  }

  const path = parsed.pathname.replace(/^\/+|\/+$/g, "").replace(/\.git$/i, "");
  const name = basename(path);
  if (!parsed.hostname || !path || !name || name === "." || name === "..") {
    throw new Error(`invalid repository URL: ${rawUrl}`);
  }

  const user = parsed.protocol === "ssh:" && parsed.username ? `${parsed.username}@` : "";
  return {
    cloneUrl:
      parsed.protocol === "ssh:"
        ? `ssh://${user}${parsed.hostname}/${path}.git`
        : `${parsed.protocol}//${parsed.host}/${path}.git`,
    key: `${parsed.hostname}/${path}`.toLowerCase(),
    name,
  };
}

export function groupRepositories(
  packages: Array<{ name: string; repository: RepositoryRef }>,
): RepositoryGroup[] {
  const groups = new Map<string, RepositoryGroup>();
  const folders = new Map<string, string>();

  for (const { name, repository } of packages) {
    const owner = folders.get(repository.name);
    if (owner && owner !== repository.key) {
      throw new Error(
        `repository folder collision: different repositories resolve to "${repository.name}"`,
      );
    }
    folders.set(repository.name, repository.key);
    const group = groups.get(repository.key);
    if (group) {
      group.packages.push(name);
    } else {
      groups.set(repository.key, { ...repository, packages: [name] });
    }
  }

  return [...groups.values()]
    .map((group) => ({ ...group, packages: [...new Set(group.packages)].sort() }))
    .sort(byName);
}

export async function findReferenceDirectories(repositoryRoot: string, targetRoot: string) {
  const found: Array<{ label: string; path: string }> = [];

  async function walk(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (!entry.isDirectory() || entry.name.startsWith(".")) {
        continue;
      }
      const path = join(directory, entry.name);
      if (REFERENCE_DIRECTORIES.has(entry.name.toLowerCase())) {
        found.push({
          label: posixPath(relative(repositoryRoot, path)),
          path: posixPath(relative(targetRoot, path)),
        });
      } else {
        await walk(path);
      }
    }
  }

  await walk(repositoryRoot);
  return found.sort((a, b) => a.path.localeCompare(b.path));
}

export async function renderIndex(repositories: IndexRepository[], targetRoot: string) {
  const sections = await Promise.all(
    [...repositories]
      .sort((a, b) => a.directory.localeCompare(b.directory))
      .map(async ({ directory, packages, root }) => {
        const references = await findReferenceDirectories(root, targetRoot);
        const links = references.length
          ? references.map((item) => `- [${escapeLabel(item.label)}](./${encodePath(item.path)})`)
          : [`- [Repository root](./${encodePath(posixPath(relative(targetRoot, root)))})`];
        return `## ${directory}

Packages: ${[...packages]
          .sort()
          .map((name) => `\`${name}\``)
          .join(", ")}

${links.join("\n")}`;
      }),
  );
  return `${INDEX_MARKER}\n\n# Package references\n\n${sections.join("\n\n")}\n`;
}

export function mergeIndexes(existing: string, generated: string): string {
  const oldIndex = splitIndex(existing);
  const newIndex = splitIndex(generated);
  const sections = new Map([...oldIndex.sections, ...newIndex.sections]);
  return `${[
    oldIndex.preamble,
    ...[...sections].sort(([a], [b]) => a.localeCompare(b)).map(([, value]) => value),
  ]
    .filter(Boolean)
    .join("\n\n")}\n`;
}

export function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

const posixPath = (path: string) => path.split(sep).join("/");
const encodePath = (path: string) => path.split("/").map(encodeURIComponent).join("/");
const escapeLabel = (label: string) =>
  label.replaceAll("\\", "\\\\").replaceAll("[", "\\[").replaceAll("]", "\\]");

function splitIndex(contents: string) {
  const matches = [...contents.matchAll(/^## (.+)$/gm)];
  const sections = new Map<string, string>();
  matches.forEach((match, index) => {
    sections.set(match[1].trim(), contents.slice(match.index, matches[index + 1]?.index).trimEnd());
  });
  return {
    preamble: contents.slice(0, matches[0]?.index ?? contents.length).trimEnd(),
    sections,
  };
}
